budget_carriers = [
                #"Sahara Airlines",
        "E5",    #"Air Arabia Egypt",
        "F5",   #"Fly540",
        "3O",    #"Air Arabia Maroc",
                #"Kulula.com",
        "JE",    #"Mango",
                #"Fastjet",
        "BJ",    #"Nouvelair",
                #"Zimbabwings",
        "Y5",    #"Golden Myanmar Airlines",
        "9C",    #"Spring Airlines",
        "UO",    #"Hong Kong Express Airways",
                #"AirAsia India",
                #"Air India Express",
                #"GoAir",
        "6E",    #"IndiGo",
        "S2",    #"JetLite",
        "SG",    #"SpiceJet",
        "QG",    #"Citilink",
        "QZ",    #"Indonesia AirAsia",
        "JT",    #"Lion Air",
                #"Tigerair Mandala",
                #"Air Do",
        "GK",    #"Jetstar Japan",
                #"Link Airs",
        "MM",    #"Peach",
        "BC",    #"Skymark Airlines",
                #"Solaseed Air",
                #"StarFlyer",
                #"Vanilla Air",
        "PQ",    #"AirAsia",
        "D7",    #"AirAsia X",
        "J8",   #"Berjaya Air",
        "FY",    #"Firefly",
        "OD",    #"Malindo Air",
                #"AirAsia Zest",
                #"Philippines AirAsia",
        "5J",    #"Cebu Pacific",
        "2p",    #"PAL Express",
                #"Tigerair Philippines",
                #"AirAsia Korea",
        "ZE",    #"Eastar Jet",
        "7C",    #"Jeju Air",
        "LJ",    #"Jin Air",
        "TW",    #"T'way Airlines",
        "3K",    #"Jetstar Asia Airways",
        "TZ",    #"Scoot",
        "TR",    #"Tigerair",
        "MJ",    #"Mihin Lanka",
        "E8",    #"City Airways",
        "DD",    #"Nok Air",
                #"Nok Mini",
        "OX",    #"Orient Thai Airlines",
                #"Solar Air",
        "FD",    #"Thai AirAsia",
        "SL",    #"Thai Lion Air",
        "BL",    #"Jetstar Pacific Airlines",
        "VJ",    #"VietJet Air",
                #"SmartWings",
        "TO",    #"Transavia.com France",
        "4U",    #"Germanwings",
        "W6",    #"Wizz Air",
        "WW",    #"WOW air",
        "FR",    #"Ryanair",
        "AP",    #"Air One",
        "BV",    #"Blue Panorama Airlines",
        "HV",    #"Transavia.com",
        "DY",    #"Norwegian Air Shuttle",
        "0B",    #"Blue Air",
        "V7",    #"Volotea",
        "VY",    #"Vueling",
        "DS",    #"easyJet Switzerland",
        "WU",    #"Wizz Air Ukraine",
        "U2",    #"easyJet",
        "BE",    #"Flybe",
        "LS",    #"Jet2.com",
                #"UP!",
        "IZ",    #"Arkia Express",
        "J9",    #"Jazeera Airways",
        "UE",    #"Nas Air",
        "PC",    #"Pegasus Airlines",
        "6G",    #"SunExpress",
        "8Q",    #"ONUR AIR",
        "KK",    #"ATLAS JET",
        "G9",    #"Air Arabia",
        "FZ",    #"flydubai",
        "FO",    #"Felix Airways",
        "TS",    #"Air Transat",
        "SW",    #"Sunwing",
                #"Interjet",
                #"VivaAerobus",
        "Y4",    #"Volaris",
                #"Magnicharters",
        "FL",    #"AirTran Airways",
        "G4",    #"Allegiant Air",
        "F9",    #"Frontier Airlines",
        "B6",    #"JetBlue",
        "WN",    #"Southwest Airlines",
        "NK",    #"Spirit Airlines",
                #"Sun Country Airlines",
        "VX",    #"Virgin America",
        "JQ",    #"Jetstar Airways",
        "TT",    #"Tigerair Australia",
        "Z8",    #"Amaszonas",
                #"Titicaca Airways",
        "AD",    #"Azul Brazilian Airlines",
                #"Gol Transportes Aereos",
        "2P",    #"PAL Airlines",
        "H2",    #"Sky Airline",
                #"AeroSantiago",
        "8E",    #"EasyFly",
                #"VivaColombia",
        "P9",    #"Peruvian Airlines",
        "2I",    #"Star Peru",
                #"Oltursa Lineas Aereas",
    ]

