budget_carriers = [
        "Sahara Airlines",
        "Air Arabia Egypt",
        "Fly540",
        "Air Arabia Maroc",
        "Kulula.com",
        "Mango",
        "Fastjet",
        "Nouvelair",
        "Zimbabwings",
        "Golden Myanmar Airlines",
        "Spring Airlines",
        "Hong Kong Express Airways",
        "AirAsia India",
        "Air India Express",
        "GoAir",
        "IndiGo",
        "JetLite",
        "SpiceJet",
        "Citilink",
        "Indonesia AirAsia",
        "Lion Air",
        "Tigerair Mandala",
        "Air Do",
        "Jetstar Japan",
        "Link Airs",
        "Peach",
        "Skymark Airlines",
        "Solaseed Air",
        "StarFlyer",
        "Vanilla Air",
        "AirAsia",
        "AirAsia X",
        "Berjaya Air",
        "Firefly",
        "Malindo Air",
        "AirAsia Zest",
        "Philippines AirAsia",
        "Cebu Pacific",
        "PAL Express",
        "Tigerair Philippines",
        "AirAsia Korea",
        "Eastar Jet",
        "Jeju Air",
        "Jin Air",
        "T'way Airlines",
        "Jetstar Asia Airways",
        "Scoot",
        "Tigerair",
        "Mihin Lanka",
        "City Airways",
        "Nok Air",
        "Nok Mini",
        "Orient Thai Airlines",
        "Solar Air",
        "Thai AirAsia",
        "Thai Lion Air",
        "Jetstar Pacific Airlines",
        "VietJet Air",
        "SmartWings",
        "Transavia.com France",
        "Germanwings",
        "Wizz Air",
        "WOW air",
        "Ryanair",
        "Air One",
        "Blue Panorama Airlines",
        "Transavia.com",
        "Norwegian Air Shuttle",
        "Blue Air",
        "Volotea",
        "Vueling",
        "easyJet Switzerland",
        "Wizz Air Ukraine",
        "easyJet",
        "Flybe",
        "Jet2.com",
        "UP!",
        "Arkia Express",
        "Jazeera Airways",
        "Nas Air",
        "Pegasus Airlines",
        "SunExpress",
        "ONUR AIR",
        "ATLAS JET",
        "Air Arabia",
        "flydubai",
        "Felix Airways",
        "Air Transat",
        "Sunwing",
        "Interjet",
        "VivaAerobus",
        "Volaris",
        "Magnicharters",
        "AirTran Airways",
        "Allegiant Air",
        "Frontier Airlines",
        "JetBlue",
        "Southwest Airlines",
        "Spirit Airlines",
        "Sun Country Airlines",
        "Virgin America",
        "Jetstar Airways",
        "Tigerair Australia",
        "Amaszonas",
        "Titicaca Airways",
        "Azul Brazilian Airlines",
        "Gol Transportes Aereos",
        "PAL Airlines",
        "Sky Airline",
        "AeroSantiago",
        "EasyFly",
        "VivaColombia",
        "Peruvian Airlines",
        "Star Peru",
        "Oltursa Lineas Aereas",
    ]

