def get_airline_image(name):

  #code = code.upper

  airlines = {
    'EIN' : {'name': 'Aer Lingus', 'image': 'aer-lingus.gif'},
    'AFL' : {'name': 'Aeroflot Russian Airlines', 'image': 'aeroflot.gif'},
    'ARG' : {'name': 'Aerolineas Argentinas', 'image': 'aerolineas-argentinas.png'},
    'AMX' : {'name': 'Aeromexico', 'image': 'aeromexico.jpg'},
    'ABY' : {'name': 'Air Arabia', 'image': 'air-arabia.jpg'},
    'AXM' : {'name': 'AirAsia', 'image': 'air-asia.png'},
    'BER' : {'name': 'Air Berlin', 'image': 'air-berlin.gif'},
    'ACA' : {'name': 'Air Canada', 'image': 'air-canada.jpg'},
    'CCA' : {'name': 'Air China', 'image': 'air-china.jpg'},
    'AFR' : {'name': 'Air France', 'image': 'air-france.jpg'},
    'AIC' : {'name': 'Air India Limited', 'image': 'air-india.jpg'},
    'MDG' : {'name': 'Air Madagascar', 'image': 'air-madagascar.gif'},
    'MAU' : {'name': 'Air Mauritius', 'image': 'air-mauritius.jpg'},
    'ANZ' : {'name': 'Air New Zealand', 'image': 'air-new-zealand.jpg'},
    'ANE' : {'name': 'Air Nostrum', 'image': 'air-nostrum.jpg'},
    'GAP' : {'name': 'Air Philippines', 'image': 'air-philippines.gif'},
    'SEY' : {'name': 'Air Seychelles', 'image': 'air-seychelles.png'},
    'TSC' : {'name': 'Air Transat', 'image': 'air-transat.jpg'},
    'TRS' : {'name': 'AirTran Airways', 'image': 'airtran.jpg'},
    'PAK' : {'name': 'Alaska Airlines', 'image': 'alaska-airlines.gif'},
    'AZA' : {'name': 'Alitalia', 'image': 'alitalia.gif'},
    'AAY' : {'name': 'Allegiant Air', 'image': 'allegiant-air.gif'},
    'AAL' : {'name': 'American Airlines', 'image': 'american-airlines.jpg'},
    'EGF' : {'name': 'American Eagle Airlines', 'image': 'american-eagle.png'},
    'ANA' : {'name': 'All Nippon Airways', 'image': 'ana.jpg'},
    'AAR' : {'name': 'Asiana Airlines', 'image': 'asiana-airlines.png'},
    'AUA' : {'name': 'Austrian Airlines', 'image': 'austrian-airlines.gif'},
    'AVA' : {'name': 'Avianca - Aerovias Nacionales de Colombia, S.A.', 'image': 'avianca.png'},
    'AHY' : {'name': 'Azerbaijan Airlines', 'image': 'azerbaijan-airlines.png'},
    'BKP' : {'name': 'Bangkok Airways', 'image': 'bangkok-airways.png'},
    'BAW' : {'name': 'British Airways', 'image': 'british-airways.jpg'},
    'BEL' : {'name': 'Brussels Airlines', 'image': 'brussels-airlines.jpg'},
    'CPA' : {'name': 'Cathay Pacific', 'image': 'cathay-pacific.jpg'},
    'CEB' : {'name': 'Cebu Pacific', 'image': 'cebu-pacific.png'},
    'CAL' : {'name': 'China Airlines', 'image': 'china-airlines.jpg'},
    'CES' : {'name': 'China Eastern Airlines', 'image': 'china-eastern.jpg'},
    'CSN' : {'name': 'China Southern Airlines', 'image': 'china-southern.jpg'},
    'CIB' : {'name': 'Condor', 'image': 'condor.jpg'},
    'CMP' : {'name': 'Copa Airlines', 'image': 'copa-airlines.jpg'},
    'CTN' : {'name': 'Croatia Airlines', 'image': 'croatia-airlines.gif'},
    'DAL' : {'name': 'Delta Air Lines', 'image': 'delta.jpg'},
    'HDA' : {'name': 'Dragonair, Hong Kong Dragon Airlines', 'image': 'dragon-air.jpg'},
    'EZY' : {'name': 'easyJet', 'image': 'easyjet.gif'},
    'UAE' : {'name': 'Emirates Airline', 'image': 'emirates.gif'},
    'ETH' : {'name': 'Ethiopian Airlines', 'image': 'ethiopian.gif'},
    'ETD' : {'name': 'Etihad Airways', 'image': 'etihad-airways.jpg'},
    'EVA' : {'name': 'EVA Air', 'image': 'eva-air.jpg'},
    'FJI' : {'name': 'Fiji Airways', 'image': 'fiji-airways.jpg'},
    'FIN' : {'name': 'Finnair', 'image': 'finnair.png'},
    'FFT' : {'name': 'Frontier Airlines', 'image': 'frontier.gif'},
    'GIA' : {'name': 'Garuda Indonesia', 'image': 'garuda-indonesia.png'},
    'GLO' : {'name': 'Gol Transportes Aereos', 'image': 'gol.jpg'},
    'GFA' : {'name': 'Gulf Air', 'image': 'gulf-air.jpg'},
    'HAL' : {'name': 'Hawaiian Airlines', 'image': 'hawaiian-airlines.png'},
    'IBE' : {'name': 'Iberia Airlines', 'image': 'iberia.png'},
    'ICE' : {'name': 'Icelandair', 'image': 'icelandair.jpg'},
    'IBU' : {'name': 'Indigo', 'image': 'indigo.jpg'},
    'JAL' : {'name': 'Japan Airlines', 'image': 'japan-airlines.png'},
    'JBU' : {'name': 'JetBlue Airways', 'image': 'jetblue.jpg'},
    'JST' : {'name': 'Jetstar Airways', 'image': 'jetstar.png'},
    'KQA' : {'name': 'Kenya Airways', 'image': 'kenya-airways.jpg'},
    'KFR' : {'name': 'Kingfisher Airlines', 'image': 'kingfisher-airlines.jpg'},
    'KLM' : {'name': 'KLM', 'image': 'klm.jpg'},
    'KAL' : {'name': 'Korean Air', 'image': 'korean-air.gif'},
    'LAN' : {'name': 'LAN Airlines', 'image': 'lan.jpg'},
    'LOT' : {'name': 'LOT Polish Airlines', 'image': 'lot.gif'},
    'DLH' : {'name': 'Lufthansa', 'image': 'lufthansa.gif'},
    'MAS' : {'name': 'Malaysia Airlines', 'image': 'malaysia.gif'},
    'MXA' : {'name': 'Mexicana de Aviacion', 'image': 'mexicana.jpg'},
    'NAX' : {'name': 'Norwegian Air Shuttle', 'image': 'norwegian.jpg'},
    'POE' : {'name': 'Porter Airlines', 'image': 'porter.jpg'},
    'QFA' : {'name': 'Qantas', 'image': 'qantas.gif'},
    'QTR' : {'name': 'Qatar Airways', 'image': 'qatar-airways.jpg'},
    'RYR' : {'name': 'Ryanair', 'image': 'ryanair.jpg'},
    'SVA' : {'name': 'Saudia', 'image': 'saudi-airlines.png'},
    'SAS' : {'name': 'Scandinavian Airlines', 'image': 'scandinavian-airlines.jpg'},
    'CSZ' : {'name': 'Shenzhen Airlines', 'image': 'shenzhen-airlines.jpg'},
    'SLK' : {'name': 'SilkAir', 'image': 'silkair.png'},
    'SIA' : {'name': 'Singapore Airlines', 'image': 'singapore-airlines.jpg'},
    'SKW' : {'name': 'SkyWest Airlines', 'image': 'skywest-airlines.png'},
    'SAA' : {'name': 'South African Airways', 'image': 'south-african-airways.png'},
    'SWA' : {'name': 'Southwest Airlines', 'image': 'southwest.jpg'},
    'NKS' : {'name': 'Spirit Airlines', 'image': 'spirit-airlines.jpg'},
    'ALK' : {'name': 'SriLankan Airlines', 'image': 'srilankan-airlines.gif'},
    'SWR' : {'name': 'Swissair', 'image': 'swissair.jpg'},
    'TAT' : {'name': 'Grupo TACA', 'image': 'taca.gif'},
    'TAM' : {'name': 'TAM Brazilian Airlines', 'image': 'tam.gif'},
    'TAP' : {'name': 'TAP Portugal', 'image': 'tap.gif'},
    'ROT' : {'name': 'Tarom', 'image': 'tarom.gif'},
    'THA' : {'name': 'Thai Airways International', 'image': 'thai-airways.jpg'},
    'TOM' : {'name': 'Thomson Airways', 'image': 'thomson-airways.jpg'},
    'TSO' : {'name': 'Transaero Airlines', 'image': 'transaero-airlines.png'},
    'THY' : {'name': 'Turkish Airlines', 'image': 'turkish-airlines.gif'},
    'UAL' : {'name': 'United Airlines', 'image': 'united-airlines.png'},
    'AWE' : {'name': 'US Airways', 'image': 'us-airways.jpg'},
    'VRD' : {'name': 'Virgin America', 'image': 'virgin-america.jpg'},
    'VOI' : {'name': 'Volaris', 'image': 'volaris.png'},
    'VLG' : {'name': 'Vueling Airlines', 'image': 'vueling.png'},
    'WJA' : {'name': 'WestJet', 'image': 'west-jet.png'},
    'WZZ' : {'name': 'Wizz Air', 'image': 'wizz-air.jpg'},
  }

  images = [ i['image'] for i in airlines.itervalues() if i['name'].lower() in name.lower() ]

  if len(images) == 1:
    return images[0]
  else:
    return None

if __name__ == "__main__":

    print get_airline_image('Wizz Air')